apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-settings
data:
  jwt-settings-issuer: Body4uHUB.Identity
  jwt-settings-audience: Body4uHUB
  jwt-settings-expirationMinutes: "60"
  cors-allowedOrigins: "http://localhost"
  rabbitmq-host: rabbitmq-service
  rabbitmq-virtualhost: /
  rabbitmq-default-user: guest
  rabbitmq-retryCount: "5"
  rabbitmq-retryIntervalInSeconds: "5"
  rabbitmq-outboxQueryMessageLimit: "100"
  rabbitmq-outboxQueryDelaySeconds: "1"